/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline": "#7f7667",
        "primary": "#775a19",
        "on-primary-container": "#4e3700",
        "surface-container-highest": "#e2e3e1",
        "on-surface-variant": "#4e4639",
        "tertiary-fixed": "#e4e2dc",
        "surface-variant": "#e2e3e1",
        "surface-container-low": "#f4f4f2",
        "primary-container": "#c5a059",
        "on-primary-fixed-variant": "#5d4201",
        "on-secondary-fixed": "#1b1c1c",
        "tertiary-fixed-dim": "#c8c6c1",
        "on-background": "#1a1c1b",
        "on-secondary": "#ffffff",
        "primary-fixed": "#ffdea5",
        "inverse-on-surface": "#f1f1ef",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#3b3b37",
        "secondary-container": "#e4e2e1",
        "on-error-container": "#93000a",
        "on-secondary-container": "#656464",
        "tertiary": "#5f5f5a",
        "surface-bright": "#f9f9f7",
        "error-container": "#ffdad6",
        "surface-tint": "#775a19",
        "surface-dim": "#dadad8",
        "surface-container": "#eeeeec",
        "on-tertiary-fixed-variant": "#474743",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "error": "#ba1a1a",
        "outline-variant": "#d1c5b4",
        "secondary-fixed-dim": "#c8c6c6",
        "secondary-fixed": "#e4e2e1",
        "inverse-surface": "#2f3130",
        "on-surface": "#1a1c1b",
        "on-primary-fixed": "#261900",
        "surface": "#f9f9f7",
        "on-secondary-fixed-variant": "#474747",
        "background": "#f9f9f7",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#1b1c18",
        "inverse-primary": "#e9c176",
        "secondary": "#5f5e5e",
        "primary-fixed-dim": "#e9c176",
        "tertiary-container": "#a6a5a0",
        "surface-container-high": "#e8e8e6"
      },
      spacing: {
        "stack-md": "1.5rem",
        "stack-lg": "3rem",
        "stack-sm": "0.5rem",
        "margin-mobile": "1rem",
        "gutter": "2rem",
        "container-max": "1280px"
      },
      fontFamily: {
        "label-sm": ["Inter", "sans-serif"],
        "display-lg": ["Libre Caslon Text", "serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Libre Caslon Text", "serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}